### ISSUE TITLE
Add a GENERATE_SWIFT environment variable for use by scripts

### ISSUE THREAD

**Issue by brockboland** [vokal/Xcode-Template#11]
We have two versions of `MOGenerator.sh`, one for each output language. There's only one version of `DevsJustWantToHaveFun.sh`, but it only outputs Objective-C.

Let's add a boolean `GENERATE_SWIFT` environment variable that's set in each of the project templates, and make use of it in those build scripts to include the `--swift` flag (or equivalent) as appropriate.

**Comment by vokal-isaac** [comment]
Here are versions of the three code-generating shell scripts, modified to look for an environment variable `VOKAL_GENERATE_SWIFT` and test if it's set to the string `true`, so that the Swift project template can set a user-defined setting at the project level setting `VOKAL_GENERATE_SWIFT` to `true` and have all the scripts generate Swift.

I'm not immediately sure, however, how to modify the templates themselves to handle this change.

[Cat2Cat.sh.txt](https://github.com/vokal/Xcode-Template/files/457454/Cat2Cat.sh.txt)
[DevsJustWantToHaveFun.sh.txt](https://github.com/vokal/Xcode-Template/files/457455/DevsJustWantToHaveFun.sh.txt)
[MOGenerator.sh.txt](https://github.com/vokal/Xcode-Template/files/457456/MOGenerator.sh.txt)

**Comment by brockboland** [comment]
`Cat2Cat.sh` and `DevsJustWantToHaveFun.sh` can both be updated in-place, in `Vokal-ObjC.xctemplate/Scripts` and `Vokal-Cocoa Touch Application Base.xctemplate/Scripts`, respectively.

`MOGenerator.sh` currently exists in both templates (in `Vokal-ObjC.xctemplate/Scripts` and `Vokal-Swift.xctemplate/Scripts`), but those separate versions can be removed and the new one dropped into the shared ancestor (`Vokal-Cocoa Touch Application Base.xctemplate/Scripts`). 

I'm not sure if that'll be all for Mogenerator, though. That script is only added to the project when the Vokoder option is checked, but since it comes with a `CoreDataUtility` helper/stub, there's different versions in Swift and Obj-C. Both templates reference `Scripts/MOGenerator.sh`, but I'm not sure if Xcode will correctly grab that file from the parent template when you create a project using one of the two child templates.

**Comment by bryanluby** [comment]
Closing as we are no longer using these code generation tools.
